name: Client CI

on:
  push:
    branches-ignore:
      - master
      - dev
    paths:
      - "Client/**"

jobs:
  job1:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.x'
        
    - name: Install MAUI Workload
      run: dotnet workload install maui-android

    - name: Build and Test
      run: |
        dotnet build ./Client -c Release
        dotnet test ./Client -c Release