name: Server CI

on:
  push:
    branches-ignore:
      - master
      - dev
    paths:
      - "Server/**"

jobs:
  job1:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.x'

    - name: Build and Test
      run: |
        dotnet build ./Server -c Release
        dotnet test ./Server -c Release