name: Server Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  job1:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0'

    - name: Build and Test
      run: |
        dotnet build ./Server --configuration Release
        dotnet test ./Server --configuration Release